language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
    - composer install -n
    - app/console doctrine:database:create
    - app/console doctrine:schema:create
    - app/console doctrine:fixtures:load
    - sleep 5

script:
    - phpunit -c app
