chabanenk0_guestbook:
    resource: "@chabanenk0GuestbookBundle/Resources/config/routing.yml"
    prefix:   /

chabanenk0_blog:
    resource: "@chabanenk0BlogBundle/Resources/config/routing.yml"
    prefix:   /

chabanenk0_test_assignment:
    resource: "@chabanenk0TestAssignmentBundle/Resources/config/routing.yml"
    prefix:   /

_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

_acme_demo2:
    resource: "@AcmeDemoBundle/Resources/config/myroute.yml"
