parameters:
    chabanenk0_test_assignment.example.class: chabanenk0\TestAssignmentBundle\Services\TestListenerService

services:
    chabanenk0_test_assignment.example:
        class: %chabanenk0_test_assignment.example.class%
        arguments: [@doctrine, @event_dispatcher]