_index:
    pattern: /
    defaults: { _controller: AcmeDemoBundle:My:index }


_first:
    pattern: /first/
    defaults: { _controller: AcmeDemoBundle:My:first }

_second:
    pattern: /second/
    defaults: { _controller: AcmeDemoBundle:My:second }

_third:
    pattern: /third/
    defaults: { _controller: AcmeDemoBundle:My:third }

_contacts:
    pattern: /contacts/
    defaults: { _controller: AcmeDemoBundle:My:contacts }

_about:
    pattern: /about/
    defaults: { _controller: AcmeDemoBundle:My:about }

_testview:
    pattern: /testview/{id}/
    defaults: { _controller: AcmeDemoBundle:My:testView }

_guestbook:
    pattern: /guestbook/
    defaults: { _controller: AcmeDemoBundle:Post:index }

_guestbook_id:
    pattern: /guestbook/{id}/{page}
    defaults: { _controller: AcmeDemoBundle:Post:index, id: -1, page: 1 }

_guestbook_pager_id:
    pattern: /posts_pager/{id}/{page}
    defaults: { _controller: AcmeDemoBundle:Post:postsPager, id: -1, page: 1 }


_postview:
    pattern:  /postview/{id}
    defaults: { _controller: AcmeDemoBundle:Post:view }


_postdelete:
    pattern:  /postdelete/{id}
    defaults: { _controller: AcmeDemoBundle:Post:delete }


_tests:
    pattern:  /tests/{id}/{page}
    defaults: { _controller: AcmeDemoBundle:My:tests, page: 1 }

_new_test_asmt:
    pattern:  /newtestasmt/
    defaults: { _controller: AcmeDemoBundle:My:newTest }

_tests_pager:
    pattern:  /tests_pager/{id}/{page}
    defaults: { _controller: AcmeDemoBundle:My:testsPager, page: 1 }
